---
# Seems that lookup does not work in vars file
#guid: "{{ lookup('env','GUID') }}"
# osp_cloud_project: "{{ guid }}-project"
#osp_cloud_project: 0ad4-project
# ansible tower issue , it can't take actual cloud tenant name . Refer https://access.redhat.com/solutions/3295691
osp_cloud_project: devstack
#guid: 0ad4

instances:
  - name: app-01.example.com
    keypair: 0ad4-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 0ad4-HostSG
    internal_network: 0ad4-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: dev
      server_type: app

  - name: app-02.example.com
    keypair: 0ad4-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 0ad4-HostSG
    internal_network: 0ad4-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: dev
      server_type: app

  - name: database-01.example.com
    keypair: 0ad4-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 0ad4-HostSG
    internal_network: 0ad4-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: dev
      server_type: db

  - name: frontend.example.com
    keypair: 0ad4-keypair
    image: rhel-8.3
    flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
    security_group: 0ad4-HostSG
    internal_network: 0ad4-dev-network
    metadata:
      AnsibleGroup: osp_instances
      deployment_name: dev
      server_type: lb
