---
# Deploy Multi-Tier Application

# Before starting - lets get the openstack inventory in-memory
- name: Include openstack instances into in-memory inventory play
  import_playbook: infra_osp_in_memory_inventory.yml

# Install and Setup postgresql server
- name: Play to setup postgresql server
  hosts: db
  tasks:
    - debug:
        msg: "Start postgresql server setup"

    - name: Setup firewall
      include_role:
        name: firewall
      vars:
        firewall_services:
          - postgresql

    - name: Setup postgresql server
      include_role:
        name: postgres

    - debug:
        msg: "Finished postgresql server setup"

