---
- name: Create OpenStack Instances
  hosts: control_node
  connection: local
  gather_facts: false
  # vars:
  #   guid: "{{ lookup('ENV','GUID') }}"
  tasks:
    # - name: Include Instance variables
    #   include_vars: instances_vars.yml

    - name: Create Server Instance
      openstack.cloud.server:
        cloud: "{{ osp_cloud_project }}"
        name: "{{ instance.name }}"
        image: "{{ instance.image }}"
        key_name: "{{ instance.keypair }}"
        flavor: "{{ instance.flavor }}"
        security_groups: "{{ instance.security_group }}"
        delete_fip: yes
        wait: no
        nics:
          - net-name: "{{ instance.internal_network }}"
        meta: "AnsibleGroup={{instance.metadata.AnsibleGroup}},deployment_name={{instance.metadata.deployment_name}},server_type={{instance.metadata.server_type}}"
        userdata: |
          #!/bin/bash
          echo "Created as part of cloud-init/userdata" > /tmp/cloud-userdata        
      loop: "{{ instances }}"
      loop_control:
        loop_var: instance

